---
- name: Ensure the download directory exists
  ansible.windows.win_file:
    path: '{{ windows_ssh_download_path }}'
    state: directory
    force: true

- name: Set TLS version for downloads
  ansible.windows.win_shell: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'

- name: Get latest OpenSSH release information from GitHub
  ansible.windows.win_uri:
    url: "https://api.github.com/repos/PowerShell/Win32-OpenSSH/releases/latest"
    method: GET
    return_content: true
  register: release_info

- name: Parse release assets and find the OpenSSH-Win64 MSI file
  ansible.builtin.set_fact:
    openssh_asset: "{{ release_info.json.assets | selectattr('name', 'search', 'OpenSSH-Win64-.*msi') | list | first }}"

- name: Set the filename and URL of the OpenSSH MSI file
  ansible.builtin.set_fact:
    openssh_msi_url: "{{ openssh_asset.browser_download_url }}"
    openssh_msi_name: "{{ openssh_asset.name }}"
    openssh_msi_path: '{{ windows_ssh_download_path }}\{{ openssh_asset.name }}'

- name: Download OpenSSH MSI file
  ansible.windows.win_get_url:
    url: "{{ openssh_msi_url }}"
    dest: "{{ openssh_msi_path }}"
    force: true

- name: Install OpenSSH
  ansible.windows.win_package:
    path: "{{ openssh_msi_path }}"
    arguments: "/qb"
    state: present

- name: Remove the OpenSSH MSI file after installation
  ansible.windows.win_file:
    path: "{{ openssh_msi_path }}"
    state: absent
